### update a existing entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json


{

  "name": "jhon Doe",
  "email": "test@test.com",
  "address": "123 berlin road",
  "dateOfBirth": "2001-02-04"
}

###